import type { Metadata } from "next";
import { Amplify } from "aws-amplify";
import { Inter } from "next/font/google";
import { Authenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";
import outputs from "@/amplify_outputs.json";
import "./app.css";

Amplify.configure(outputs);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (<html lang="en">
    <body>      
      <Authenticator>
        {children}
      </Authenticator>
    </body>
  </html>)
}
